typewrite "We are now in the remote system! However, do we know where we really are? We can use the 'pwd' command to print the current working directory. Here is an example: "
demonstrate "pwd"
typewrite "Try it on your own!"
make_user_say "pwd"
typewrite "Alright, now we know where we are in the filesystem. But, what is in our current directory?"
typewrite "We can use 'ls' to list the stuff in our current directory. Let me show you."
demonstrate "ls"
typewrite "Now it's your turn!" 
make_user_say "ls" 
