typewrite "Another thing that catches my attention is the 'stuff' folder. "
typewrite "To read what is in the 'stuff' directory, we can use 'ls stuff' to see what's in there. Here's how it works: "
demonstrate "ls stuff"
typewrite "You know what to do!"
make_user_say "ls stuff"
typewrite "Let's say we want to work with things in the 'stuff' directory. We can obviously 'cat' out the contents of the files by including the path: "
demonstrate "cat stuff/stuff1.txt"
typewrite "Or, we can also change our working directory and then do the commands from there. "
demonstrate "pwd"
demonstrate "cd stuff"
demonstrate "pwd"
demonstrate "ls"
demonstrate "cat stuff1.txt"
cd ..
typewrite "Now you try it!" 
make_user_say "cat stuff/stuff2.txt"
make_user_say "cd stuff"
make_user_say "cat stuff2.txt"
typewrite "As you might have noticed, the shell prompt shows you the name of the highest level directory, just in case you might be lost!"
typewrite "Ok! Now that we have looked at the stuff here, we can go back to the previous directory by using 'cd ..' , which moves us back to the parent directory. Here is how it looks like: "
demonstrate "cd .."
typewrite "Now it's your turn!" 
cd stuff;
make_user_say "cd .."
